/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as ChatPeerIdRouteImport } from './routes/chat.$peerId'
import { Route as ChatGroupGroupIdRouteImport } from './routes/chat.group.$groupId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPeerIdRoute = ChatPeerIdRouteImport.update({
  id: '/chat/$peerId',
  path: '/chat/$peerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatGroupGroupIdRoute = ChatGroupGroupIdRouteImport.update({
  id: '/chat/group/$groupId',
  path: '/chat/group/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/chat/$peerId': typeof ChatPeerIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/chat/': typeof ChatIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/chat/group/$groupId': typeof ChatGroupGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/chat/$peerId': typeof ChatPeerIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/chat': typeof ChatIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/chat/group/$groupId': typeof ChatGroupGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/chat/$peerId': typeof ChatPeerIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/chat/': typeof ChatIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/chat/group/$groupId': typeof ChatGroupGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/notifications'
    | '/settings'
    | '/chat/$peerId'
    | '/groups/$groupId'
    | '/posts/$postId'
    | '/profile/$userId'
    | '/chat/'
    | '/groups/'
    | '/chat/group/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/notifications'
    | '/settings'
    | '/chat/$peerId'
    | '/groups/$groupId'
    | '/posts/$postId'
    | '/profile/$userId'
    | '/chat'
    | '/groups'
    | '/chat/group/$groupId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/notifications'
    | '/settings'
    | '/chat/$peerId'
    | '/groups/$groupId'
    | '/posts/$postId'
    | '/profile/$userId'
    | '/chat/'
    | '/groups/'
    | '/chat/group/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  NotificationsRoute: typeof NotificationsRoute
  SettingsRoute: typeof SettingsRoute
  ChatPeerIdRoute: typeof ChatPeerIdRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  ChatGroupGroupIdRoute: typeof ChatGroupGroupIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$peerId': {
      id: '/chat/$peerId'
      path: '/chat/$peerId'
      fullPath: '/chat/$peerId'
      preLoaderRoute: typeof ChatPeerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/group/$groupId': {
      id: '/chat/group/$groupId'
      path: '/chat/group/$groupId'
      fullPath: '/chat/group/$groupId'
      preLoaderRoute: typeof ChatGroupGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  NotificationsRoute: NotificationsRoute,
  SettingsRoute: SettingsRoute,
  ChatPeerIdRoute: ChatPeerIdRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  ChatIndexRoute: ChatIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  ChatGroupGroupIdRoute: ChatGroupGroupIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
